// Complete IPL 2024 Player Data (220 players) with exact base prices from Excel sheet
const IPL_PLAYERS_DATA = {
    allRounders: [
        { name: 'Ravichandran Ashwin', team: 'CSK', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Rachin Ravindra', team: 'CSK', basePrice: 1.5, country: 'New Zealand', capped: 'Capped' },
        { name: 'Ravindra Jadeja', team: 'CSK', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Shivam Dube', team: 'CSK', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Jamie Overton', team: 'CSK', basePrice: 1.5, country: 'England', capped: 'Capped' },
        { name: 'Axar Patel', team: 'DC', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Rahul Tewatia', team: 'GT', basePrice: 4.0, country: 'India', capped: 'Capped' },
        { name: 'Venkatesh Iyer', team: 'KKR', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Varun Chakravarthy', team: 'KKR', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Andre Russell', team: 'KKR', basePrice: 2.0, country: 'West Indies', capped: 'Capped' },
        { name: 'Arshin Kulkarni', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Mitchell Marsh', team: 'LSG', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Raj Bawa', team: 'MI', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Hardik Pandya', team: 'MI', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Glenn Maxwell', team: 'PBKS', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Marcus Stoinis', team: 'PBKS', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Liam Livingstone', team: 'RCB', basePrice: 2.0, country: 'England', capped: 'Capped' },
        { name: 'Yashasvi Jaiswal', team: 'RR', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Harshal Patel', team: 'SRH', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Pat Cummins', team: 'SRH', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Yuvraj Chaudhary', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Nitish Rana', team: 'RR', basePrice: 1.5, country: 'India', capped: 'Capped' },
        { name: 'Sam Curran', team: 'CSK', basePrice: 2.0, country: 'England', capped: 'Capped' },
        { name: 'Krunal Pandya', team: 'RCB', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Washington Sundar', team: 'GT', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Vijay Shankar', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Abdul Samad', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Jayant Yadav', team: 'GT', basePrice: 0.75, country: 'India', capped: 'Capped' },
        { name: 'Mitchell Santner', team: 'MI', basePrice: 2.0, country: 'New Zealand', capped: 'Capped' },
        { name: 'Suryansh Shedge', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Aaron Hardie', team: 'PBKS', basePrice: 1.25, country: 'Australia', capped: 'Capped' },
        { name: 'Manoj Bhandage', team: 'RCB', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Jacob Bethell', team: 'RCB', basePrice: 1.25, country: 'England', capped: 'Capped' },
        { name: 'Brydon Carse', team: 'SRH', basePrice: 1.0, country: 'England', capped: 'Capped' },
        { name: 'Kamindu Mendis', team: 'SRH', basePrice: 0.75, country: 'Sri Lanka', capped: 'Capped' },
        { name: 'Harpreet Brar', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Ramakrishna Ghosh', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Karim Janat', team: 'GT', basePrice: 0.75, country: 'Afghanistan', capped: 'Capped' },
        { name: 'Mahipal Lomror', team: 'GT', basePrice: 0.5, country: 'India', capped: 'Capped' },
        { name: 'Ashutosh Sharma', team: 'DC', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Marco Jansen', team: 'PBKS', basePrice: 1.25, country: 'South Africa', capped: 'Capped' },
        { name: 'Vipraj Nigam', team: 'DC', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Sameer Rizvi', team: 'DC', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Sai Sudharsan', team: 'GT', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'M Shahrukh Khan', team: 'GT', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Ramandeep Singh', team: 'KKR', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Ayush Badoni', team: 'LSG', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Naman Dhir', team: 'MI', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Tilak Varma', team: 'MI', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Shashank Singh', team: 'PBKS', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Riyan Parag', team: 'RR', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Abhishek Sharma', team: 'SRH', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Nitish Kumar Reddy', team: 'SRH', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Nishant Sindhu', team: 'GT', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Anshul Kamboj', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Arshad Khan', team: 'GT', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Anukul Roy', team: 'KKR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Kamlesh Nagarkoti', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Darshan Nalkande', team: 'DC', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Musheer Khan', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Swapnil Singh', team: 'RCB', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Priyansh Arya', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Rajvardhan Hangargekar', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Yudhvir Singh', team: 'RR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Manvanth Kumar', team: 'DC', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Ajay Mandal', team: 'DC', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Praveen Dubey', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Madhav Tiwari', team: 'DC', basePrice: 0.4, country: 'India', capped: 'Uncapped' },
        { name: 'Tripurana Vijay', team: 'DC', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Mohit Rathee', team: 'RCB', basePrice: 0.3, country: 'India', capped: 'Uncapped' }
    ],
    batsmen: [
        { name: 'Rahul Tripathi', team: 'CSK', basePrice: 0.75, country: 'India', capped: 'Capped' },
        { name: 'Devon Conway', team: 'CSK', basePrice: 2.0, country: 'New Zealand', capped: 'Capped' },
        { name: 'Ruturaj Gaikwad', team: 'CSK', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'MS Dhoni', team: 'CSK', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Jake Fraser-McGurk', team: 'DC', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Harry Brook', team: 'DC', basePrice: 2.0, country: 'England', capped: 'Capped' },
        { name: 'KL Rahul', team: 'DC', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Jos Buttler', team: 'GT', basePrice: 2.0, country: 'England', capped: 'Capped' },
        { name: 'Shubman Gill', team: 'GT', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Manish Pandey', team: 'KKR', basePrice: 0.75, country: 'India', capped: 'Capped' },
        { name: 'Rahmanullah Gurbaz', team: 'KKR', basePrice: 2.0, country: 'Afghanistan', capped: 'Capped' },
        { name: 'Quinton de Kock', team: 'KKR', basePrice: 2.0, country: 'South Africa', capped: 'Capped' },
        { name: 'Rinku Singh', team: 'KKR', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Aiden Markram', team: 'LSG', basePrice: 2.0, country: 'South Africa', capped: 'Capped' },
        { name: 'David Miller', team: 'LSG', basePrice: 1.5, country: 'South Africa', capped: 'Capped' },
        { name: 'Rishabh Pant', team: 'LSG', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Nicholas Pooran', team: 'LSG', basePrice: 2.0, country: 'West Indies', capped: 'Capped' },
        { name: 'Suryakumar Yadav', team: 'MI', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Rohit Sharma', team: 'MI', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Pyla Avinash', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Vishnu Vinod', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Shreyas Iyer', team: 'PBKS', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Jitesh Sharma', team: 'RCB', basePrice: 1.0, country: 'India', capped: 'Capped' },
        { name: 'Phil Salt', team: 'RCB', basePrice: 2.0, country: 'England', capped: 'Capped' },
        { name: 'Devdutt Padikkal', team: 'RCB', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Virat Kohli', team: 'RCB', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Sanju Samson', team: 'RR', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Shimron Hetmyer', team: 'RR', basePrice: 2.0, country: 'West Indies', capped: 'Capped' },
        { name: 'Ishan Kishan', team: 'SRH', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Heinrich Klaasen', team: 'SRH', basePrice: 2.0, country: 'South Africa', capped: 'Capped' },
        { name: 'Travis Head', team: 'SRH', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Ajinkya Rahane', team: 'KKR', basePrice: 1.5, country: 'India', capped: 'Capped' },
        { name: 'Vansh Bedi', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Faf du Plessis', team: 'DC', basePrice: 2.0, country: 'South Africa', capped: 'Capped' },
        { name: 'Ryan Rickelton', team: 'MI', basePrice: 1.0, country: 'South Africa', capped: 'Capped' },
        { name: 'Karun Nair', team: 'DC', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Donovan Ferreira', team: 'DC', basePrice: 0.75, country: 'South Africa', capped: 'Capped' },
        { name: 'Glenn Phillips', team: 'GT', basePrice: 2.0, country: 'New Zealand', capped: 'Capped' },
        { name: 'Rovman Powell', team: 'KKR', basePrice: 1.5, country: 'West Indies', capped: 'Capped' },
        { name: 'Josh Inglis', team: 'PBKS', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'C Andre Siddarth', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Tristan Stubbs', team: 'DC', basePrice: 2.0, country: 'South Africa', capped: 'Uncapped' },
        { name: 'Abishek Porel', team: 'DC', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Anuj Rawat', team: 'GT', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Luvnith Sisodia', team: 'KKR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Angkrish Raghuvanshi', team: 'KKR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Aryan Juyal', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Nehal Wadhera', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Prabhsimran Singh', team: 'PBKS', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Rajat Patidar', team: 'RCB', basePrice: 1.0, country: 'India', capped: 'Uncapped' },
        { name: 'Dhruv Jurel', team: 'RR', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Aniket Verma', team: 'SRH', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Atharva Taide', team: 'SRH', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Robin Minz', team: 'MI', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Shaik Rasheed', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Himmat Singh', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Swastik Chikara', team: 'RCB', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Krishnan Shrijith', team: 'MI', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Shubham Dubey', team: 'RR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Harnoor Singh', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Matthew Breetzke', team: 'LSG', basePrice: 0.75, country: 'South Africa', capped: 'Uncapped' },
        { name: 'Sachin Baby', team: 'SRH', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Vaibhav Suryavanshi', team: 'RR', basePrice: 1.1, country: 'India', capped: 'Uncapped' },
        { name: 'Kunal Singh Rathore', team: 'RR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Abhinav Manohar', team: 'SRH', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Kumar Kushagra', team: 'GT', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Bevon Jacobs', team: 'MI', basePrice: 0.3, country: 'South Africa', capped: 'Uncapped' },
        { name: 'Dewald Brevis', team: 'CSK', basePrice: 2.0, country: 'South Africa', capped: 'Uncapped' }
    ],
    bowlers: [
        { name: 'Mukesh Kumar', team: 'DC', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Mohit Sharma', team: 'DC', basePrice: 0.5, country: 'India', capped: 'Capped' },
        { name: 'T Natarajan', team: 'DC', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Mitchell Starc', team: 'DC', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Kuldeep Yadav', team: 'DC', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Kulwant Khejroliya', team: 'GT', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Prasidh Krishna', team: 'GT', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Mohammed Siraj', team: 'GT', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Kagiso Rabada', team: 'GT', basePrice: 2.0, country: 'South Africa', capped: 'Capped' },
        { name: 'Rashid Khan', team: 'GT', basePrice: 2.0, country: 'Afghanistan', capped: 'Capped' },
        { name: 'Umran Malik', team: 'KKR', basePrice: 0.75, country: 'India', capped: 'Capped' },
        { name: 'Anrich Nortje', team: 'KKR', basePrice: 2.0, country: 'South Africa', capped: 'Capped' },
        { name: 'Sunil Narine', team: 'KKR', basePrice: 2.0, country: 'West Indies', capped: 'Capped' },
        { name: 'Akash Deep', team: 'LSG', basePrice: 1.0, country: 'India', capped: 'Capped' },
        { name: 'Shamar Joseph', team: 'LSG', basePrice: 0.75, country: 'West Indies', capped: 'Capped' },
        { name: 'Avesh Khan', team: 'LSG', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Ravi Bishnoi', team: 'LSG', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Lizaad Williams', team: 'MI', basePrice: 0.75, country: 'South Africa', capped: 'Capped' },
        { name: 'Allah Ghazanfar', team: 'MI', basePrice: 0.75, country: 'Afghanistan', capped: 'Capped' },
        { name: 'Deepak Chahar', team: 'MI', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Jasprit Bumrah', team: 'MI', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Lockie Ferguson', team: 'PBKS', basePrice: 2.0, country: 'New Zealand', capped: 'Capped' },
        { name: 'Yuzvendra Chahal', team: 'PBKS', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Arshdeep Singh', team: 'PBKS', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Nuwan Thushara', team: 'RCB', basePrice: 0.75, country: 'Sri Lanka', capped: 'Capped' },
        { name: 'Josh Hazlewood', team: 'RCB', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Bhuvneshwar Kumar', team: 'RCB', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Lungi Ngidi', team: 'RCB', basePrice: 1.0, country: 'South Africa', capped: 'Capped' },
        { name: 'Wanindu Hasaranga', team: 'RR', basePrice: 2.0, country: 'Sri Lanka', capped: 'Capped' },
        { name: 'Maheesh Theekshana', team: 'RR', basePrice: 2.0, country: 'Sri Lanka', capped: 'Capped' },
        { name: 'Jofra Archer', team: 'RR', basePrice: 2.0, country: 'England', capped: 'Capped' },
        { name: 'Sandeep Sharma', team: 'RR', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Jaydev Unadkat', team: 'SRH', basePrice: 1.0, country: 'India', capped: 'Capped' },
        { name: 'Adam Zampa', team: 'SRH', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Rahul Chahar', team: 'SRH', basePrice: 1.0, country: 'India', capped: 'Capped' },
        { name: 'Mohammed Shami', team: 'SRH', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Shreyas Gopal', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Gerald Coetzee', team: 'GT', basePrice: 1.25, country: 'South Africa', capped: 'Capped' },
        { name: 'Dushmantha Chameera', team: 'DC', basePrice: 0.75, country: 'Sri Lanka', capped: 'Capped' },
        { name: 'Karn Sharma', team: 'MI', basePrice: 0.5, country: 'India', capped: 'Capped' },
        { name: 'Nathan Ellis', team: 'CSK', basePrice: 1.25, country: 'Australia', capped: 'Capped' },
        { name: 'Akash Singh', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Reece Topley', team: 'MI', basePrice: 0.75, country: 'England', capped: 'Capped' },
        { name: 'Kuldeep Sen', team: 'PBKS', basePrice: 0.75, country: 'India', capped: 'Capped' },
        { name: 'Kwena Maphaka', team: 'RR', basePrice: 0.75, country: 'South Africa', capped: 'Capped' },
        { name: 'Fazalhaq Farooqi', team: 'RR', basePrice: 2.0, country: 'Afghanistan', capped: 'Capped' },
        { name: 'Mayank Markande', team: 'KKR', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Trent Boult', team: 'MI', basePrice: 2.0, country: 'New Zealand', capped: 'Capped' },
        { name: 'Simarjeet Singh', team: 'SRH', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Vaibhav Arora', team: 'KKR', basePrice: 0.3, country: 'India', capped: 'Capped' },
        { name: 'Tushar Deshpande', team: 'RR', basePrice: 1.0, country: 'India', capped: 'Capped' },
        { name: 'Noor Ahmad', team: 'CSK', basePrice: 2.0, country: 'Afghanistan', capped: 'Capped' },
        { name: 'Yash Thakur', team: 'PBKS', basePrice: 0.4, country: 'India', capped: 'Capped' },
        { name: 'Matheesha Pathirana', team: 'CSK', basePrice: 2.0, country: 'Sri Lanka', capped: 'Uncapped' },
        { name: 'Harshit Rana', team: 'KKR', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Mayank Yadav', team: 'LSG', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Mohsin Khan', team: 'LSG', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Vignesh Puthur', team: 'MI', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Abhinandan Singh', team: 'RCB', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Rasikh Salam', team: 'RCB', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Yash Dayal', team: 'RCB', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Akash Madhwal', team: 'RR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Ashok Sharma', team: 'RR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Khaleel Ahmed', team: 'CSK', basePrice: 2.0, country: 'India', capped: 'Uncapped' },
        { name: 'Gurnoor Brar', team: 'GT', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Manimaran Siddharth', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Suyash Sharma', team: 'RCB', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Mukesh Choudhary', team: 'GT', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Prince Yadav', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Digvesh Rathi', team: 'LSG', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Ashwani Kumar', team: 'MI', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Xavier Bartlett', team: 'PBKS', basePrice: 0.75, country: 'Australia', capped: 'Uncapped' },
        { name: 'Zeeshan Ansari', team: 'SRH', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Satyanarayana Raju', team: 'MI', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Ishant Sharma', team: 'GT', basePrice: 0.75, country: 'India', capped: 'Uncapped' },
        { name: 'Arjun Tendulkar', team: 'MI', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Eshan Malinga', team: 'SRH', basePrice: 1.2, country: 'India', capped: 'Uncapped' },
        { name: 'Manav Suthar', team: 'GT', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Gurjapneet Singh', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Kumar Kartikeya', team: 'RR', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Vijaykumar Vyshak', team: 'PBKS', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Dewald Brevis', team: 'CSK', basePrice: 2.0, country: 'South Africa', capped: 'Uncapped' },
        { name: 'Mustafizur Rahman', team: 'DC', basePrice: 1.0, country: 'Bangladesh', capped: 'Capped' },
        { name: 'Urvil Patel', team: 'CSK', basePrice: 0.3, country: 'India', capped: 'Uncapped' },
        { name: 'Corbin Bosch', team: 'MI', basePrice: 0.5, country: 'South Africa', capped: 'Capped' },
        { name: 'Richard Gleeson', team: 'MI', basePrice: 0.5, country: 'England', capped: 'Capped' },
        { name: 'Jonny Bairstow', team: 'MI', basePrice: 2.0, country: 'England', capped: 'Capped' },
        { name: 'Will Jacks', team: 'MI', basePrice: 1.0, country: 'England', capped: 'Capped' },
        { name: 'Mayank Agarwal', team: 'RCB', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'Tim David', team: 'RCB', basePrice: 2.0, country: 'Australia', capped: 'Capped' },
        { name: 'Shardul Thakur', team: 'LSG', basePrice: 2.0, country: 'India', capped: 'Capped' },
        { name: 'William O\'rourke', team: 'LSG', basePrice: 1.0, country: 'New Zealand', capped: 'Capped' }
    ]
};
